### PR TITLE
updates for generic Chef12 stacks

### PR DESCRIPTION
**Pull request by izakp**
updates for generic Chef12 stacks - drop migrate arg to deploy command, change logs_root and add deploy_root in config, drop Chef11 layer dependencies

### CODE REVIEW

**Comment by joeyAghion** [comment]
This looks OK. My only hesitation is around changing the default from `rails-app`, which is a standard Opworks-provided layer name, to just `rails`. If I understand correctly, these changes target the new Chef 12-style stacks that don't use standard layer names anyway, so there's decent rationale for this.

The `-app` makes more clear that we're talking about application servers instead of background workers or other instances of the Rails environment. I'm fine with this in any case, just wanted to mention that.

**Comment by izakp** [comment]
@joeyAghion yes I considered that, and since Chef 12 stacks no longer provide default layer templates, it's up to the user to configure both the layer name as well as the cookbooks that are run on the layer.  That said, I think changing the layer name makes it clear whether this is a Chef 11 or Chef 12 stack.

**Comment by joeyAghion** [comment]
👍 This is probably worth a minor version bump in any case.

**Comment by izakp** [comment]
Let's merge so I can reference `github.com/artsy/momentum` in Gemini's `Gemfile`, then we can add a Changelog, bump version and release

**Pull request merged**
